var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                   xxx            xxx             xxx           ",
   "                                  xx!xx          xx!xx           xx!xx          ",
   "                                  x!!!x          x!!!x           x!!!x          ",
   "                                  xx!xx          xx!xx           xx!xx          ",
   "                                   xvx            xvx             xvx     xxxx  ",
   "    @                                                                      xxx  ",
   "  xxx                                                                       xx  ",
   "  x                     o                                                    x  ",
   "  x                                         o               o              o x  ",
   "  x                     o     x                          x                   x  ",
   "  x            ^              xx                        x      xx            x  ",
   "  xxxxxxxxxxxxxxxxxxxxx***xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  
  ["                                x                                                ",
   "                               x!x                                               ",
   "                        x     xx!xx                                              ",
   "                       x!x     xvx                                               ",
   "                      xx!xx                                                      ",
   "                       xvx                                                       ",
   "                x                                                                ",
   "               x!x                                                               ",
   "              xx!xx                                                        o     ",
   "               xvx                                                               ",
   "                               xxx                                       xxxx    ",
   "                              x   x                                     x        ",
   "                             x     x                                   x         ",
   "                            x       xxx                              xx          ",
   "                           x           xxx                        xx             ",
   "                          x                  o                                   ",
   " @                     xxx                  xxx          o     xx                ",
   "xxx                   x                                      xx                  ",
   "                     x                             xxxxxxxxx                     ",
   "                    x                                                            ",
   "     xxx           x                                                             ",
   "     xxx     xxxxxx                     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "      x      x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         ",
   "!!!!!!x!!!!!!x                          x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x         "],
 
  ["                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                           @                                                     ",
   "                           xxx                                                   ",
   "                                            x     x                              ",
   "                              x       x                                          ",
   "                                x                    x                           ",
   "                                               o  x                              ",
   "                                               x                                 ",
   "                                     x     x      x     x                        ",
   "                                                     x                           ",
   "                                                             x                   ",
   "                                                                                 ",
   "                                   x                x      x      x              ",
   "                                          x                                      ",
   "                             x                  x             x        x         ",
   "                                                   x!!x    x!!x                  ",
   "xxx                     x           x         x    xxxx    xxxx      x        x  ",
   "xxx                                                                              ",
   "xxx                    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o  x!!!!!!!!!!!!!!!!!!!x",
   "xxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxx",
   "xxx                      x             x            x             x        x     ",
   "xxx                      x             x            x   xxx       x        x     ",
   "xxx                      x                          x          o  x        x     ",
   "xxx                      x        xx                x        x    x        x     ",
   "xxx                      x                                    xxx x        x     ",
   "xxx                      x            xx                                   x     ",
   "xxx                      x            xxx           x                      x     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
   
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
